services:
  app:
    build: .
    restart: always
    ports:
      - 7300:3000

  database:
    image: postgres:13
    volumes:
      - ./postgres/users/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  systems_health:
    image: redis:6
    restart: always
    command: redis-server