services:
  app:
    build: .
    restart: always
    ports:
      - 7300:3000
  
  influx:
    image: influxdb:2
    hostname: influx
    volumes:
      - ./influx/lib:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=battlestats
      - DOCKER_INFLUXDB_INIT_BUCKET=league

  users:
    image: redis:6
    hostname: users
    volumes:
      - ./redis/users/data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  battles:
    image: redis:6
    hostname: battles
    volumes:
      - ./redis/battles/data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning
  fleets:
    image: redis:6
    hostname: fleets
    volumes:
      - ./redis/fleets/data:/data
    restart: always
    command: redis-server --save 60 1 --loglevel warning