services:
  app:
    build: .
    restart: always
    ports:
      - 7300:3000
    depends_on:
      - database
      - systems
    
  task_runner:
    build:
      context: .
      dockerfile: runnerDockerfile
    restart: always
    depends_on: 
       - database
       - systems

  database:
    image: postgres:13
    volumes:
      - ./postgres/users/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: battlestats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  systems:
    image: redis:6
    restart: always
    command: redis-server